import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {createHandler,validateRequest,CONSENT_VERSION,hashToken,randomToken} from '../supabase/functions/kapukai-community-apply/handler.mjs';
export const OWNER=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','test-tenant','test-subject'];
const read=p=>readFile(new URL(p,import.meta.url),'utf8');
export async function setup(open=true){const db=new PGlite();for(const f of ['./legacy_fixture.sql','../sql/proposed_schema.sql','../supabase/migrations/20261008150526_community_signup_interests.sql','../supabase/migrations/20261008183145_community_applications.sql','./lifecycle-fixture.sql','../supabase/migrations/20261008191433_workshop_lifecycle.sql'])await db.exec(await read(f));await db.exec('update kapukai_application_config set enabled=true');if(open)await db.exec('update kapukai_workshop_config set enabled=true');return db;}
export async function create(db,overrides={}){const token=randomToken();const body={action:'request',email:'person-'+crypto.randomUUID()+'@example.test',kind:'assistance',service_interest:'tools',requested_support:'free',request_id:crypto.randomUUID(),consent_version:CONSENT_VERSION,source_path:'/community/assistance',started_at:Date.now()-2000,adult:true,privacy_acknowledged:true,human_review_acknowledged:true,...overrides};const v=validateRequest(body).value;if(!v)throw new Error('Invalid fixture');const r=(await db.query('select kapukai_application_request($1,$2,$3,$4,$5,$6) r',[v.email,await hashToken(token),v.request_id,JSON.stringify(v.application),v.consent_version,v.source_path])).rows[0].r;await db.query('select kapukai_application_token($1,$2)',[await hashToken(token),'confirm']);return {id:r.application_id,token,body};}
export async function snap(db,id){return (await db.query('select kapukai_workshop_snapshot($1) r',[id])).rows[0].r;}
export async function owner(db,id,action,payload={},revision=null,requestId=crypto.randomUUID(),principal=OWNER){if(revision===null)revision=(await snap(db,id)).revision;return (await db.query('select kapukai_workshop_owner_action($1,$2,$3,$4,$5,$6,$7,$8,$9) r',[...principal,id,action,revision,requestId,JSON.stringify(payload)])).rows[0].r;}
export async function applicant(db,a,action,payload={},revision=null,requestId=crypto.randomUUID()){if(revision===null)revision=(await snap(db,a.id)).revision;return (await db.query('select kapukai_workshop_applicant($1,$2,$3,$4,$5) r',[await hashToken(a.token),action,revision,requestId,JSON.stringify(payload)])).rows[0].r;}
export const http=(body)=>new Request('https://example.test/apply',{method:'POST',headers:{Origin:'https://kapukai-community.vercel.app','Content-Type':'application/json'},body:JSON.stringify(body)});
export function handler(db){return createHandler({rpc:async(name,args)=>{const keys={kapukai_application_token:['p_token_hash','p_action'],kapukai_workshop_applicant:['p_token_hash','p_action','p_expected_revision','p_request_id','p_payload']}[name];if(!keys)throw new Error('Unexpected RPC');return(await db.query('select '+name+'('+keys.map((_,i)=>'$'+(i+1)).join(',')+') r',keys.map(k=>k==='p_payload'?JSON.stringify(args[k]):args[k]))).rows[0].r;},isOpen:async()=>true});}
