'use strict';

const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sourceData = window.KAPUKAI_SOURCES || {sources:[]};
const caseData = window.KAPUKAI_CASES || {cases:[]};
const sourceMap = new Map(sourceData.sources.map(s => [s.id,s]));
const sourceLink = (id, label) => {
  const s=sourceMap.get(id);
  return s ? `<a href="${escapeHTML(s.url)}" target="_blank" rel="noopener">${escapeHTML(label||s.title)}</a>` : '';
};

const nodes = {
  people:{title:'Power has a public purpose.',lead:'Begin with the human interest affected by the decision. Then identify the legal structure that gives a particular office its powers and limits.',check:['Who is affected, and what legally protected interest is at stake?','Which public office claims authority?','What written legal source allocates this power?'],example:'A child’s safety, relationships, and access to care must remain visible while a specific decision is examined.',status:'Foundational principle. Individual disagreement does not itself withdraw lawful jurisdiction.',sources:['declaration','fl_constitution']},
  declaration:{title:'Founding principle ≠ filing authority.',lead:'The Declaration explains principles of legitimacy and consent. It is not itself a standalone cause of action or a procedural vehicle for obtaining a court order.',check:['Use the Declaration to explain the public purpose of power.','Identify the actual constitutional, statutory, or other enforceable right.','Find the separate legal authority for the requested remedy.'],example:'“Consent of the governed” frames the question. A motion still needs the correct provision, forum, and procedural conditions.',status:'Historical foundation, visually separate from binding authority.',sources:['declaration','constitution']},
  us_constitution:{title:'Allocation and limits come first.',lead:'The U.S. Constitution distributes federal legislative, executive, and judicial power. Specific exercises of power still need their operative legal basis.',check:['Which branch and office are involved?','What enumerated power, right, or constitutional limit is relevant?','What makes this dispute judicially reviewable?'],example:'Article III does not make every complaint a federal case. Jurisdiction, standing, a claim, and available relief remain separate inquiries.',status:'Federal constraints can apply to state action without turning state courts into federal agencies.',sources:['constitution','bill_of_rights','fourteenth']},
  fl_constitution:{title:'State authority has its own structure.',lead:'Florida’s Constitution recognizes political power in the people, protects due process and access to courts, and allocates judicial power. Federal constitutional limits also constrain state action.',check:['Which state constitutional allocation or limit applies?','Which circuit, district, agency, or official has the relevant role?','What statute or rule supplies action-specific conditions?'],example:'A Florida dependency matter follows its own jurisdiction and procedure. The federal APA does not turn it into a federal agency proceeding.',status:'Parallel constitutional structure; no automatic federal chain of command.',sources:['fl_constitution','fourteenth','apa_701']},
  federal_law:{title:'Find the operative federal provision.',lead:'Name the precise statute, regulation, rule, or controlling decision. A broad program purpose is not the same as a discrete duty owed by a named actor.',check:['Identify the section, subsection, version, and applicability.','Separate a mandatory act from discretion over its outcome.','Check special review statutes and other required procedural gates.'],example:'A duty to decide an application may support a request for a decision. It does not necessarily require approval of the application.',status:'The federal agency route depends on the agency and the actual legal scheme.',sources:['apa_555','apa_704','apa_706','norton']},
  florida_law:{title:'Find the exact state-law checkpoint.',lead:'For a Chapter 39 proceeding, connect the particular action to the relevant statute and current juvenile or appellate rule. Different stages have different predicates.',check:['Is this custody, shelter, adjudication, disposition, treatment, or review?','What findings, documents, notice, or hearing does that branch require?','What is the correct route for this alleged defect?'],example:'After a qualifying finding of agency noncompliance with a written case plan, §39.701(2)(d)3 separates discretionary contempt from required compliance plans and an explanation.',status:'A “best interests” label does not replace the required conditions for the specific action.',sources:['fl_39_013','fl_39_701','fl_juvenile_rules']},
  delegation:{title:'Trace the power to the office.',lead:'A title alone does not explain the scope of a person’s authority. Trace the enactment, appointment, assignment, order, or lawful delegation that applies.',check:['What power was given to this office?','Was this person assigned to exercise it?','What subject, territory, duration, or conditions limit it?'],example:'An evaluator may recommend; a court may decide. A recommendation becomes an operative restriction only through the applicable decision authority.',status:'An unresolved delegation question is a research gap, not an automatic legal conclusion.',sources:['constitution','fl_constitution']},
  actor:{title:'Make responsibility identifiable.',lead:'Record who did what in which capacity. Separate the author of a report, the decision-maker, the person executing the decision, and the person responsible for review.',check:['Actor, office, capacity, and decision date.','Document or communication showing the action.','Who can change the record, ruling, or operational consequence?'],example:'A records custodian can correct a data field. That correction may still require a separate decision-maker to reconsider a court or agency outcome.',status:'One card per consequential action helps prevent responsibility from disappearing between roles.',sources:[]},
  action:{title:'Start with one consequential event.',lead:'The smallest useful unit is one act or omission by one identified authority holder, at one procedural stage, affecting a person’s protected interest.',check:['Name the actor and the specific action or required act not performed.','Record when it happened and its human consequence.','Identify the source, fact, and procedure needed to assess it.'],example:'“The agency did not provide the assigned service” is a traceable question when tied to the operative case plan, evidence of availability, and a review stage.',status:'A missing link remains a question until evidence and the applicable legal test resolve it.',sources:['fl_39_701']},
  predicates:{title:'Convert the provision into conditions.',lead:'A predicate is a condition that must be established before a particular power or duty operates. Keep each condition separate and source-linked.',check:['What must be true, who must determine it, and under which standard?','What evidence supports, contradicts, or leaves it unknown?','Do an exception, emergency branch, or different procedural stage apply?'],example:'“The court finds agency noncompliance” is a different trigger from “a person alleges agency noncompliance.” Record which one exists.',status:'Evidence unavailable to you ≠ evidence nonexistent ≠ legally insufficient evidence.',sources:['fl_39_701','fl_39_402']},
  procedure:{title:'The process has its own conditions.',lead:'Notice, service, filing, hearings, findings, and time rules determine how a legal question reaches a body able to decide it.',check:['What document is recognized at this stage, and who may file it?','Who must receive it, by which method, with what proof?','Which exact event starts each clock, and what changes or does not change it?'],example:'Florida dependency rehearing under Rule 8.265 does not toll appeal time. Separate clocks must be checked against the actual order and current rules.',status:'Receipt is not acceptance of the merits. Filing is not a stay or a granted remedy.',sources:['fl_juvenile_rules','fl_appellate_rules']},
  remedy:{title:'Separate relief from implementation.',lead:'A competent body must have power to grant the particular relief requested. Then verify whether the authorized remedy changed the affected person’s circumstances.',check:['Identify the claim or motion, competent forum, and available relief.','Record the ruling, reasons, implementation owner, and time rule.','Identify dependent records and decisions; verify correction where authorized.'],example:'A corrected source entry does not prove every recipient updated its copy. Track downstream correction as an assurance control unless a specific law or order makes it mandatory.',status:'Duty, private right of action, jurisdiction, immunity, and remedy are separate questions.',sources:['apa_702','section1983','state_judgment_review']}
};

function renderNode(id) {
  const n=nodes[id]; if(!n) return;
  $$('.diagram-node').forEach(b=>{const on=b.dataset.node===id;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});
  $('#node-detail').innerHTML=`<h2 id="inspect-title">${escapeHTML(n.title)}</h2><p class="detail-lead">${escapeHTML(n.lead)}</p><div class="inspect-block"><h3>WHAT TO ESTABLISH</h3><ul>${n.check.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul></div><div class="inspect-example"><strong>WORKED DISTINCTION</strong><p>${escapeHTML(n.example)}</p></div><p class="inspect-status">${escapeHTML(n.status)}</p>${n.sources.length?`<div class="route-links">${n.sources.map(id=>sourceLink(id)).join('')}</div>`:''}`;
}
$$('[data-node]').forEach(b=>b.addEventListener('click',()=>renderNode(b.dataset.node)));
renderNode('action');

const steps={
 record:{title:'Preserve what happened.',text:'Build an event ledger from lawfully obtained material. Separate observation, report, inference, and an official finding.',items:['Keep original correspondence, docket copies, records, and authorized transcripts.','Identify the date, actor, exact action, source, and practical consequence.','Audio or video recording needs its own legal and court-rule check. Florida covered communications have consent and exception rules.'],output:'Output: event ledger + evidence index'},
 classify:{title:'Test one action against one requirement.',text:'Compare the act or omission with a sourced legal condition. Label what is supported, disputed, missing, inapplicable, or unknown.',items:['Distinguish factual error, missing predicate, excess authority, procedural defect, delay, and order noncompliance.','Separate “must act” from “may choose this outcome.”','Do not treat an alleged defect as an adjudicated violation or proof of intent.'],output:'Output: predicate matrix + uncertainty register'},
 invoke:{title:'Use the process that activates the duty.',text:'Identify a preexisting legal duty and the recognized application, motion, petition, objection, or other vehicle that presents it.',items:['Name the duty holder, exact act, provision, and trigger.','Check eligibility, completeness, filing, recipient, service, and separate deadlines.','A private demand does not create jurisdiction, liability, or a binding deadline.'],output:'Output: duty card + supported document + receipt/service evidence'},
 enforce:{title:'Ask a competent body for authorized relief.',text:'Match the alleged defect with the forum’s actual power. Review, correction, compulsion, interim relief, discipline, and damages are different routes.',items:['Check jurisdiction, standing, reviewability, waiver or immunity, venue, and applicable procedural prerequisites.','Request a specific act or remedy the body has power to grant.','Track the written ruling and any separate review period. Do not assume an automatic stay.'],output:'Output: ruling/order or documented denial + preserved review route'},
 verify:{title:'Confirm the consequence changed.',text:'The remedy has an operational finish line. Identify what must happen, who owns implementation, and what proves completion.',items:['Check the ordered act, usable service, corrected record, or restored access.','Trace known copies and dependent decisions; distinguish required corrections from proposed assurance measures.','Keep unresolved consequences assigned to the decision-maker who can address them.'],output:'Output: completion evidence + correction reach + unresolved items'}
};
function renderStep(id){const s=steps[id];if(!s)return;$$('[data-step]').forEach(b=>{const active=b.dataset.step===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});$('#workflow-panel').setAttribute('aria-labelledby','step-'+id);$('#workflow-panel').innerHTML=`<div><h3>${s.title}</h3><p>${s.text}</p><p class="output-line">${s.output}</p></div><ul>${s.items.map(t=>`<li>${t}</li>`).join('')}</ul>`;}
$$('[data-step]').forEach(b=>b.addEventListener('click',()=>renderStep(b.dataset.step)));
function tabKeys(selector, render, key){const tabs=$$(selector);tabs.forEach((b,i)=>b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i-1+tabs.length)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].focus();render(tabs[next].dataset[key]);}}));}
tabKeys('[data-step]',renderStep,'step');renderStep('record');

const routes={
 dependency:{tag:'FLORIDA / CONDITIONAL JUDICIAL ROUTE',title:'Begin with the existing dependency docket.',text:'For a Chapter 39 court order, identify the actual order, stage, alleged defect, and relief before selecting a procedural vehicle. In Hillsborough County the trial forum is the Thirteenth Judicial Circuit; qualifying appellate review goes to the Second DCA.',gates:[['Before selecting a document','Determine final or nonfinal status, required findings, preservation, rendition, and applicable juvenile/appellate rules.'],['Possible document sequence','Operative order + sourced issue + supporting record → appropriate motion, notice of appeal, or eligible writ → required service → ruling and implementation. These are alternative branches, not one automatic sequence.'],['Keep clocks separate','Rule 8.265 rehearing does not toll appeal time. An appeal generally does not automatically stay the order. Check the specific rule and any exception.']],sources:['fl_39_013','fl_39_510','fl_juvenile_rules','fl_appellate_rules','fl_second_dca']},
 caseplan:{tag:'FLORIDA / AGENCY CASE-PLAN DUTY',title:'Separate the agency’s duty from the court’s finding.',text:'Where an operative Chapter 39 written case plan assigns an agency duty, preserve its terms, evidence of performance or barriers, and the existing judicial-review record. A request through the appropriate party and procedure can seek findings and authorized relief.',gates:[['Predicate to establish','Identify the written duty, responsible agency, actual failure, contrary evidence, and any later order or modification.'],['Conditional official output','If the court finds agency noncompliance, §39.701(2)(d)3 requires compliance plans and a showing why safe return is unavailable; contempt is discretionary.'],['Completion to verify','Obtain the written review order, track required submissions, and confirm the service is actually usable. Noncompliance alone does not establish every condition for return.']],sources:['fl_39_701','fl_juvenile_rules']},
 federal_delay:{tag:'FEDERAL / RESEARCH-GATED INACTION ROUTE',title:'Identify a discrete act that the agency is legally required to take.',text:'A federal agency’s unresolved required decision may raise a failure-to-act question. The governing program law and special review scheme come first. The APA is not a universal route for state courts or state agencies.',gates:[['Prove the trigger','Preserve the operative provision, complete application or qualifying request, receipt, applicable time rule, exceptions, and current status.'],['Check the review scheme','Identify statutory forum, standing, reviewability, waiver, venue, prescribed administrative process, and any adequate alternative remedy. Some statutes route review directly to a court of appeals.'],['Bound the requested relief','Potential §706(1) relief addresses discrete agency action legally required. A duty to decide is not necessarily a duty to grant the desired result.']],sources:['apa_551','apa_555','apa_701','apa_702','apa_706','norton']},
 federal_action:{tag:'FEDERAL / REVIEW OF COMPLETED AGENCY ACTION',title:'Check reviewability before choosing a court.',text:'For a completed federal agency decision, identify the controlling program statute and whether the action is reviewable under that scheme or the APA. A written denial and its reasons may matter, but receipt of a denial does not resolve all review prerequisites.',gates:[['Assemble the action record','Identify the decision, actor, grounds, operative law, notice, and any administrative review instructions.'],['Apply the actual gates','Review statutory routes, finality and adequate-remedy questions under §704, exceptions under §701, standing, waiver, venue, and required administrative steps.'],['Request authorized relief','Use the complaint or petition the proper forum recognizes, complete service, and identify a remedy within the court’s power. Interim relief has its own requirements.']],sources:['apa_555','apa_701','apa_702','apa_704','apa_706']},
 rights:{tag:'FEDERAL RIGHTS / SEPARATE CLAIM ANALYSIS',title:'A rights claim is not an automatic appeal route.',text:'A potential claim under 42 U.S.C. §1983 requires a specific federal right and deprivation under color of state law. A federal district court does not act as a general appellate court for an adverse state judgment.',gates:[['Define the alleged deprivation','Identify the federal right, defendant’s conduct, injury, causation, and evidence. Not every statutory shortcoming supplies an enforceable federal right.'],['Check barriers and forum','Assess jurisdiction, standing, defendant status, immunity, relief, venue, preclusion, abstention, and applicable procedural requirements.'],['Separate available remedies','Damages, prospective relief, correction, and reversal of a state ruling have different requirements. A disciplinary complaint does not itself change the court order.']],sources:['section1983','standing','judicial_immunity','state_judgment_review']},
 unresolved:{tag:'ROUTE NOT ESTABLISHED',title:'The selected combination needs a more specific legal source.',text:'This educational atlas has not established a filing route for these selections. Do not infer a court, deadline, mandatory response, or remedy from the government label alone.',gates:[['Define the one event','Name the actual actor, subject, act or omission, date, procedural posture, and human consequence.'],['Find the controlling scheme','Identify the enabling statute, applicable rules, review provision, and the actual order or notice.'],['Resolve before filing','Determine the recognized document, competent forum, eligibility, time trigger, service, available relief, and any parallel clock.']],sources:['constitution','fl_constitution']}
};
function renderRoute(){const f=new FormData($('#route-form'));let id='unresolved';if(f.get('subject')==='rights'&&f.get('system')==='florida')id='rights';else if(f.get('system')==='florida'&&f.get('subject')==='dependency'&&f.get('remedy')!=='damages'){if(f.get('actor')==='court'&&f.get('action')==='order')id='dependency';else if(f.get('actor')==='agency'&&f.get('action')==='failure')id='caseplan';}else if(f.get('system')==='federal'&&f.get('actor')==='agency'&&f.get('subject')==='administration'&&f.get('remedy')!=='damages'){id=f.get('action')==='failure'?'federal_delay':f.get('action')==='decision'?'federal_action':'unresolved';}if(f.get('stage')==='unknown')id='unresolved';const r=routes[id];$('#route-result').innerHTML=`<span class="route-badge">${r.tag}</span><h3>${r.title}</h3><p>${r.text}</p><div class="route-gates">${r.gates.map(([title,text])=>`<div class="route-gate"><strong>${title}</strong><p>${text}</p></div>`).join('')}</div><div class="route-links">${r.sources.map(s=>sourceLink(s)).join('')}</div>`;}
$('#route-form').addEventListener('submit',e=>{e.preventDefault();renderRoute();});renderRoute();

const card=$('#decision-card');
const fields=$$('input,textarea,select',card);
function cardValues(){return Object.fromEntries(new FormData(card));}
function updateProgress(){const count=fields.filter(f=>f.value.trim()).length;$('#card-progress').textContent=`${count} of ${fields.length} fields entered`;}
card.addEventListener('input',updateProgress);card.addEventListener('change',updateProgress);card.addEventListener('submit',e=>e.preventDefault());updateProgress();
const example={decisionId:'ART-01-B • SYNTHETIC',jurisdiction:'Fictional family court exercise; training rules only',actorRole:'Westhaven Family Support Agency • assigned service provider',actionDate:'Agency has not made an approved course available by training day D7',record:'At D12: the D0 order directed the agency to make an approved course available without participant cost by D7. Jordan contacted the agency on D2. The provider reported on D5 that no approved place exists before D45. A D9 entry says “failed to engage” without mentioning those facts. No other referral is in the supplied packet.',evidence:'B1: fictional order. B2: D2 acknowledged enrollment request. B3: D5 provider response. B4: D9 case entry. B5: fictional procedural card.',evidenceStatus:'Mixed — explain in the record',authorityProvision:'Fictional D0 order and TR-B1–TR-B3. These are classroom rules, not real filing authorities.',predicateFacts:'Agency duty: approved, available, no participant cost, within 7 training days. Check for additional referrals, later modifications, or missing evidence. Jordan’s contact and attendance obligations are separate.',limits:'The packet does not establish intentional obstruction. Existing order remains operative. An agency email does not amend it.',duty:'Agency: make approved course available as directed. Court: decide supported requests under the fictional procedural card.',dutyType:'Mixed — separate each legal verb',dutyTrigger:'D0 fictional court order; agency assignment and receipt must be supported by the packet.',deadlineSource:'Training order: course by D7; Jordan contact by D3, attendance conditioned on available course within D30; review D21. Actual cases require governing-rule analysis.',competentForum:'Assigned fictional court in the existing case under TR-B1. No federal filing route is established.',requestedRelief:'Available approved course; accurate record of access barriers; clarification or modification of deadline where the court authorizes it.',recipientService:'TR-B1: written request identifies order and relief, attaches exhibits, delivered to all listed parties under exercise service instructions. Receipt does not prove relief granted.',expectedOutput:'A court decision on supported requested relief; an actual approved course place if directed. Do not assume sanctions.',outcome:'Not yet decided. Course remains unavailable in supplied packet; ask whether other options or a later order exist.',correctionReach:'Verify course start and accessibility; verify operative court instructions; seek correction of incomplete case entry where appropriate; assess any dependent decision separately.'};
$('#load-example').addEventListener('click',()=>{Object.entries(example).forEach(([k,v])=>{if(card.elements.namedItem(k))card.elements.namedItem(k).value=v;});updateProgress();$('#card-status').textContent='Synthetic Case B loaded. These training rules are not real filing instructions.';});
let clearArmed=false;
$('#clear-card').addEventListener('click',()=>{if(fields.some(f=>f.value.trim())&&!clearArmed){clearArmed=true;$('#clear-card').textContent='Confirm clear';$('#card-status').textContent='Select Confirm clear to discard this tab’s entries. Export first if you want to keep them.';setTimeout(()=>{clearArmed=false;$('#clear-card').textContent='Clear entries';},7000);return;}card.reset();updateProgress();clearArmed=false;$('#clear-card').textContent='Clear entries';$('#card-status').textContent='Entries cleared.';});
$('#export-card').addEventListener('click',()=>{const values=cardValues();const data={schema:'kapukai.authority-to-remedy.card.v1',exportedAt:new Date().toISOString(),scope:'Educational documentation. No legal conclusion or filing-readiness determination.',...values};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='kapukai-action-duty-remedy-card.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);$('#card-status').textContent='JSON export prepared. Your entries have not been submitted.';});
$('#print-card').addEventListener('click',()=>{const rows=fields.map(f=>{const label=f.closest('label');const labelText=label?label.childNodes[0].textContent.trim():f.name;return `<div class="print-field"><strong>${escapeHTML(labelText)}</strong><p class="${f.value.trim()?'':'empty'}">${escapeHTML(f.value.trim()||'Not entered')}</p></div>`;}).join('');$('#print-output').innerHTML=`<h1>Action Duty Remedy Card</h1><p class="print-meta">KAPUKAI • Educational pilot • ${new Date().toLocaleDateString()}<br>One action or inaction. Fields entered do not establish legal sufficiency. Verify law, facts, forum, and procedure.</p>${rows}`;window.print();});

const caseIds={record:'ART-01-A',plan:'ART-01-B',delay:'ART-01-C'};
const caseSummaries={record:'The source log identifies R-814. An import assigns the incidents to R-184, and three summaries copy the imported error. The correction request and review of the resulting transport decision have different training clocks.',plan:'An order assigns duties to both the caregiver and the agency. The caregiver contacts the agency on time, but the approved course has no place available before D45. A case entry calls this a failure to engage.',delay:'An invented federal office acknowledges a complete application and a written determination due D20. At D24 the portal still shows pending. An online template claims silence means approval and automatic money damages.'};
function renderScenario(id){const c=caseData.cases.find(c=>c.id===caseIds[id]);if(!c)return;$$('[data-scenario]').forEach(b=>{const active=b.dataset.scenario===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});$('#scenario-panel').setAttribute('aria-labelledby','scenario-'+id);const key=Object.entries(c.answer_key).filter(([k,v])=>typeof v==='string');$('#scenario-panel').innerHTML=`<div class="scenario-content"><div><p class="eyebrow">${escapeHTML(c.id)} / CURRENT TRAINING DAY ${escapeHTML(c.current_day)}</p><h3>${escapeHTML(c.title)}</h3><p>${escapeHTML(caseSummaries[id])}</p><p class="small-case-note">All people, offices, training rules, and time periods in this packet are fictional.</p></div><div class="scenario-task"><h4>TEAM OUTPUT</h4><p>${escapeHTML(c.assignment)}</p><ol><li>One action trace and one duty card</li><li>A route plan with separately tracked clocks</li><li>A proposed output and a remedy-closure check</li><li>One uncertainty another team must challenge</li></ol></div></div><details class="scenario-key"><summary>Open the source packet (${c.packet.length} documents)</summary><div class="packet-list">${c.packet.map(p=>`<article><h4>${escapeHTML(p.id)} · ${escapeHTML(p.type)} <span>${escapeHTML(p.date)}</span></h4><p>${escapeHTML(p.text)}</p></article>`).join('')}</div></details><details class="scenario-key"><summary>Facilitator key: reveal after team review</summary>${key.map(([k,v])=>`<p><strong>${escapeHTML(k.replace(/_/g,' ')).replace(/^./,s=>s.toUpperCase())}.</strong> ${escapeHTML(v)}</p>`).join('')}<p><strong>Common errors:</strong> ${escapeHTML(c.answer_key.common_errors.join('; '))}.</p></details>`;}
$$('[data-scenario]').forEach(b=>b.addEventListener('click',()=>renderScenario(b.dataset.scenario)));tabKeys('[data-scenario]',renderScenario,'scenario');renderScenario('record');

function renderAssets(){const assets=window.KAPUKAI_ASSETS||[];$('#asset-grid').innerHTML=assets.map(a=>`<article class="asset-card"><span class="asset-status ${a.status==='ready'?'ready':''}">${a.status==='ready'?'FILE READY':a.status==='preparing'?'IN PREPARATION':'PLANNED'} · ${escapeHTML(a.format)}</span><h3>${escapeHTML(a.title)}</h3><p>${escapeHTML(a.description)}</p>${a.status==='ready'&&a.file?`<a href="${escapeHTML(a.file)}" download>Download ${escapeHTML(a.title.toLowerCase())}</a>`:'<span class="pending">Download appears when the file is ready</span>'}</article>`).join('');}renderAssets();

function renderSources(query=''){const q=query.trim().toLowerCase();const list=sourceData.sources.filter(s=>[s.title,s.publisher,s.summary,s.id].join(' ').toLowerCase().includes(q));$('#source-count').textContent=`${list.length} of ${sourceData.sources.length} sources`;$('#source-list').innerHTML=list.length?list.map(s=>`<article class="source-item"><h3><a href="${escapeHTML(s.url)}" target="_blank" rel="noopener">${escapeHTML(s.title)}</a></h3><p>${escapeHTML(s.summary)}</p><span class="source-meta">${escapeHTML(s.publisher)} · ${escapeHTML(s.edition)} · checked ${escapeHTML(s.checked_date)}</span></article>`).join(''):'<p class="source-item">No source matches that search. Try a section number or a broader topic.</p>';}
$('#source-search').addEventListener('input',e=>renderSources(e.target.value));renderSources();
if('IntersectionObserver' in window){const links=$$('.section-nav a');const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id));}}},{rootMargin:'-15% 0px -70% 0px',threshold:0});$$('main>.section').forEach(s=>observer.observe(s));}
