from pathlib import Path
import shutil
P=Path(__file__).parent/'public'
ORIGIN='https://kapukai.org'
ROUTES={'':'community','community':'join','join':'confirm','privacy':'community/privacy','practice':'community/practice'}
def public_path(path): return ROUTES.get(path,path)
def page(path,title,description,body,script=True):
    path=public_path(path)
    d=P/path;d.mkdir(exist_ok=True,parents=True)
    canonical=ORIGIN+('/'+path.strip('/')+'/' if path else '/')
    scripts=['app.js'] if script is True else ([script] if isinstance(script,str) else [])
    scripts_html=''.join('<script src="/assets/community/'+name+'" defer></script>' for name in scripts)
    noindex='<meta name="robots" content="noindex, nofollow">' if path in ['confirm','community/apply','community/operate'] else ''
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>{title} | Kapukai</title><meta name="description" content="{description}"><meta property="og:title" content="{title} | Kapukai"><meta property="og:description" content="{description}"><meta property="og:url" content="{canonical}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary">{noindex}<link rel="canonical" href="{canonical}"><link rel="icon" href="/assets/community/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/community/style.css"></head><body><a class="skip-link" href="#main-content">Skip to content</a><header><a class="brand" href="/community/"><img src="/assets/community/favicon.svg" alt=""><span>KAPUKAI<br>Governance Lab</span></a><nav aria-label="Main"><a href="/community/practice/">Tools</a><a href="https://kapukai.org/infrastructure/">Explore</a><a href="/community/learn/">Learn</a><a href="/community/">Participate</a><a href="https://kapukai.org/founder/">About</a></nav></header><div class="community-bar"><span>The Workshop</span><nav aria-label="Workshop"><a href="/community/">Overview</a><a href="/community/assistance/">Get help</a><a href="/community/reviewers/">Review &amp; witness</a><a href="/community/contact/">Contact</a><a href="/community/status/">Service status</a></nav></div><main id="main-content">{body}</main><footer><div><strong>Kapukai Governance Lab</strong><br>Engineering tools, learning and public systems research. No legal advice.</div><div><a href="https://kapukai.org/">kapukai.org</a> · <a href="/community/contact/">Contact &amp; website directory</a><br><a href="mailto:architect@kapukai.org">architect@kapukai.org</a> · <a href="/community/privacy/">Privacy &amp; your choices</a></div></footer>{scripts_html}</body></html>'''
    for old,new in [('href="/privacy/', 'href="/community/privacy/'), ('href="/practice/', 'href="/community/practice/'), ('href="/files/', 'href="/community/files/')]: html=html.replace(old,new)
    (d/'index.html').write_text(html)
page('','Choose how to join','Apply for Kapukai tool testing or receive practical proposals for public decisions people can inspect, challenge and correct.','''<p class="eyebrow">Choose what is useful to you</p><h1>Better tools.<br>More usable remedies.</h1><p class="lede">Two ways to take part in Kapukai. Choose your emails separately. No case files, legal history or payment needed to join.</p><div class="cards"><section class="panel"><p class="tag">Help test the tools</p><h2>Kapukai Tester Circle</h2><p>Request invitations to try document tools using fictional cases. Help us check timelines, attribution, saving and corrections.</p><p class="small">An application for future test invitations. Each invitation will name the tool, free testing access and its limits.</p><a class="button" href="/testers/">Apply for tester invitations</a></section><section class="panel"><p class="tag">Follow the proposed remedies</p><h2>The Remedy Brief</h2><p>Practical proposals for public decisions people can inspect, challenge and correct. Each edition explores a different mechanism or tool.</p><p class="small">Every other week once publication begins, with a monthly digest option. You can unsubscribe at any time.</p><a class="button" href="/newsletter/">Subscribe to the brief</a></section></div>''',False)
for kind in ['testers','newsletter']:
    test=kind=='testers'
    title='Apply to the Tester Circle' if test else 'Subscribe to The Remedy Brief'
    heading='Help make useful<br>tools better.' if test else 'A practical remedy.<br>One edition at a time.'
    lede='Request free testing invitations for affidavit drafting, timeline and evidence organization tools. Start with fictional cases and tell us what needs to work better.' if test else 'Explore how public records become classifications, obligations and enforcement, and how corrections can reach the decisions they changed.'
    primary='tester_invites' if test else 'remedy_brief'
    other='remedy_brief' if test else 'tester_invites'
    primarylabel='Email me invitations to test Kapukai tools.' if test else 'Email me The Remedy Brief.'
    otherlabel='Also email me The Remedy Brief. Optional.' if test else 'Also invite me to test Kapukai tools. Optional.'
    tools='''<fieldset id="tool-choices"><legend>Tools you are interested in testing</legend><div class="tools"><label class="check"><input type="checkbox" name="tool" value="affidavit">Affidavit drafting</label><label class="check"><input type="checkbox" name="tool" value="timeline">Timelines</label><label class="check"><input type="checkbox" name="tool" value="evidence_dossier">Evidence organization</label></div></fieldset>'''
    steps='''<ol class="steps"><li><strong>Choose your invitations.</strong><br>Confirm your email and keep newsletter permission separate.</li><li><strong>Wait for a suitable test.</strong><br>An invitation will explain access, scope and what feedback is useful.</li><li><strong>Use fictional practice cases.</strong><br>Check the tool without sharing a real family’s records.</li></ol><div class="notice">Joining is an application, not immediate tool access. No payment to join. Test outputs are practice drafts, not documents approved for filing.</div><a href="/practice/">Download two fictional practice cases →</a>''' if test else '''<ol class="steps"><li><strong>Understand the mechanism.</strong><br>Keep source records, allegations, inferences and findings distinguishable.</li><li><strong>Use a concrete remedy.</strong><br>Explore protected access, correction receipts and independent review.</li><li><strong>Choose the pace.</strong><br>Receive the regular edition or a monthly digest. Leave whenever you want.</li></ol><div class="notice">The series discusses proposed reforms. It does not claim that a model bill is enacted law or decide anyone’s individual case.</div>'''
    form=f'''<section class="panel"><h2>{'Request an invitation' if test else 'Choose your subscription'}</h2><p class="small">You will be asked to confirm your email before these choices take effect.</p><form id="signup" data-source="/{kind}" data-primary="{primary}"><div class="field"><label for="email">Email address</label><input type="email" id="email" name="email" autocomplete="email" maxlength="254" required></div><label class="check"><input type="checkbox" name="topic" value="{primary}" required><span>{primarylabel}</span></label><label class="check"><input type="checkbox" name="topic" value="{other}"><span>{otherlabel}</span></label>{tools}<div class="field" id="cadence-field"><label for="cadence">Newsletter frequency</label><select name="cadence" id="cadence"><option value="every_other_week">Every other week</option><option value="monthly">Monthly digest</option></select></div><label class="check"><input type="checkbox" id="adult" required><span>I am 18 or older and have read the <a href="/privacy/">signup privacy notice</a>.</span></label><div class="hp" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><button class="full" type="submit">Send my confirmation link</button><p id="status" class="status" role="status" aria-live="polite"></p></form><p class="small">Only your email, choices and confirmation history are needed. Do not send a story, case number or court document here.</p></section>'''
    page(kind,title,lede,f'<div class="layout"><section><p class="eyebrow">{"Kapukai Tester Circle" if test else "The Remedy Brief"}</p><h1>{heading}</h1><p class="lede">{lede}</p>{steps}</section>{form}</div>')
page('join','Confirm your choices','Confirm or withdraw the email permissions you requested from Kapukai.','''<div class="manage"><p class="eyebrow">Your email choices</p><h1 id="manage-title">Confirm your choices.</h1><div class="panel"><p id="manage-status" role="status" aria-live="polite">Checking this link…</p><div id="manage-details" hidden><div id="scope-list"></div><button id="confirm" type="button">Confirm these choices</button><button id="revoke" class="button secondary" type="button">Withdraw these choices</button><p class="small">This page changes only the purposes attached to this link. It does not authorize case sharing or change unrelated services.</p></div></div><p><a href="/join/">Choose a new signup or request a fresh confirmation link</a></p></div>''')
page('privacy','Signup privacy','What Kapukai collects when you request updates, volunteer opportunities, classes, webinars or connection.','''<div class="manage"><p class="eyebrow">Signup privacy</p><h1>Your choices stay separate.</h1><p>Kapukai Governance Lab collects your email address, selected email purposes, tool interests when supplied, newsletter frequency, and the times and versions of confirmation or withdrawal. We use these records to carry out your request and document your choices.</p><h2>What this form does</h2><p>Tester invitations, The Remedy Brief, volunteer opportunities, free class and webinar notices, and collaboration follow-ups are separate permissions. Dates and volunteer assignments are announced separately. Joining one does not subscribe you to the other. A purchase, download or interest in testing does not authorize public sharing of your story.</p><h2>How confirmation works</h2><p>Postmark delivers a confirmation link. Your selected purposes become active only after you confirm them. The confirmation page also offers withdrawal. Keep that private link to manage its choices, or contact us for help. A new request cannot silently add permissions to an existing address.</p><h2>What we do not collect here</h2><p>This signup has no case upload or story field. Do not send names of children, case numbers, court files, private addresses or sensitive narratives. Downloaded fictional practice cases need no signup.</p><h2>Storage and your requests</h2><p>Supabase holds these records in Kapukai’s existing project. Postmark handles delivery. Access is restricted to the service and authorized operators. This page uses no advertising pixels or optional behavioral analytics.</p><p>For withdrawal, access or deletion assistance, email <a href="mailto:architect@kapukai.org">architect@kapukai.org</a>. We may retain the minimum suppression and consent history needed to honor your choices. Confirmation links expire after 48 hours. A valid link can withdraw its selected purposes for up to 180 days. Expiring a link does not delete the underlying record. Contact us for a data request; we retain the minimum consent and suppression history needed to honor your choices. Do not use this form to submit a legal emergency.</p><p class="small">Notice version: kapukai-scoped-v2-2026-10-08.</p></div>''',False)
page('practice','Fictional practice cases','Download two fully fictional scenarios to test timelines, attribution and correction without sharing real case records.','''<div class="manage"><p class="eyebrow">Practice without private records</p><h1>Test the mechanism.</h1><p class="lede">Use these invented scenarios to check what a document tool preserves, misses or assumes. Every person and event is fictional.</p><div class="panel"><h2>Case 1 · A timeline discrepancy</h2><p>A portal records acceptance on Day2. An agency records receipt on Day4 and calls the submission late. The tool should preserve both sources and identify what remains unresolved.</p><a class="button" href="/files/synthetic_case_01.txt" download>Download case 1</a></div><div class="panel" style="margin-top:20px"><h2>Case 2 · Allegation or finding</h2><p>An attributed allegation becomes a “confirmed” event in a later automated summary. The tool should flag that unsupported change and preserve the denial and reviewer’s limited conclusion.</p><a class="button" href="/files/synthetic_case_02.txt" download>Download case 2</a></div><section class="divider"><h2>Using a real case as inspiration</h2><p>Replacing names with Person1 and addresses with Address1 makes a record pseudonymous. Dates, case numbers, quotations, unusual events and metadata may still identify someone.</p><p>For the initial tests, use the supplied fictional cases or invent a new scenario around a general process problem. A real-case adaptation requires a separate check that sharing is lawful and identifying details have been removed. Do not upload sealed, restricted or confidential records through this signup.</p><p><a href="/files/synthetic_tester_guide.md" download>Download the testing guide</a> · <a href="/files/expected_results.json" download>Download expected results</a></p></section></div>''',False)
files=P/'community'/'files';files.mkdir(exist_ok=True)
for name in ['synthetic_case_01.txt','synthetic_case_02.txt','synthetic_tester_guide.md','expected_results.json']:
    source=Path(__file__).parent/'assets'/'files'/name
    if source.exists(): shutil.copy(source,files/name)
    elif not (files/name).exists(): raise FileNotFoundError(name)
print('Created 6 static routes and practice downloads')
